services:

  mazu_link_light_frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    # volumes:
      # - ./frontend:/app
      # - /app/node_modules
    environment:
      - NODE_ENV=development
    # command: sh -c "npm install && npm run start"
    ports:
      - "3456:3000"
    networks:
      - app-network
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

networks:
  app-network:
  shared-network:
    external: true