services:
  weaviate-test:
    image: semitechnologies/weaviate:latest
    container_name: weaviate-test
    ports:
      - "8081:8080"
    environment:
      - AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED=true
      - PERSISTENCE_DATA_PATH=/var/lib/weaviate
      - QUERY_DEFAULTS_LIMIT=25
      - DEFAULT_VECTORIZER_MODULE=text2vec-transformers
      - ENABLE_MODULES=text2vec-transformers
      - TRANSFORMERS_INFERENCE_API=http://t2v-transformers-test:8080
    volumes:
      - ./search_test/db:/var/lib/weaviate
    networks:
      - app-network

  t2v-transformers-test:
    image: semitechnologies/transformers-inference:snowflake-snowflake-arctic-embed-l-onnx
    environment:
      - ENABLE_CUDA=0
    networks:
      - app-network

networks:
  app-network:
  shared-network:
    external: true